
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ee.ttu.tud.idu0080.transport;

import java.time.LocalDate;

import logging.ServiceLogger;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-05T09:37:05.514+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "transport",
                      portName = "transportSOAP",
                      targetNamespace = "http://idu0080.tud.ttu.ee/transport/",
                      wsdlLocation = "file:/C:/Projektid/IDU0080_4/BPTeenused/WebContent/transport.wsdl",
                      endpointInterface = "ee.ttu.tud.idu0080.transport.Transport")
                      
public class TransportImpl implements Transport {

    /* (non-Javadoc)
     * @see ee.ttu.tud.idu0080.transport.Transport#transport(java.lang.String  pakkumusId )*
     */
    public java.lang.String transport(java.lang.String pakkumusId) { 
    	ServiceLogger.log("Start transport");
        try {
        	LocalDate now = LocalDate.now();
        	ServiceLogger.log("Offer: [" + pakkumusId +"] vastav tellimus registreeritud.\n"
        			+ "Saadetise tracking number: [" + pakkumusId.toLowerCase() + "#" + now + "]");
        	ServiceLogger.log("End transport");
            return pakkumusId.toLowerCase() + "#" + now;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
