
package ee.ttu.tud.idu0080.bp;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-04-21T14:29:08.510+03:00
 * Generated source version: 2.7.18
 * 
 */
 
public class Bp_BpSOAP_Server{

    protected Bp_BpSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BpImpl();
        String address = "http://localhost:8085/BpService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Bp_BpSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
