
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ee.ttu.tud.idu0080.kuller;

import java.net.URL;
import java.util.List;
import java.util.stream.Collectors;

import javax.xml.namespace.QName;

import logging.ServiceLogger;
import ttu.idu0080.order.server.Courier;
import ttu.idu0080.order.server.CourierService;
import ttu.idu0080.order.server.CourierServiceService;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-04T18:34:31.601+03:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "kuller",
                      portName = "kullerSOAP",
                      targetNamespace = "http://idu0080.tud.ttu.ee/kuller/",
                      wsdlLocation = "file:/C:/Projektid/IDU0080_4/BPTeenused/WebContent/kuller.wsdl",
                      endpointInterface = "ee.ttu.tud.idu0080.kuller.Kuller")
                      
public class KullerImpl implements Kuller {

    private static final QName SERVICE_NAME = new QName("http://server.order.idu0080.ttu/", "CourierServiceService");
    
    /* (non-Javadoc)
     * @see ee.ttu.tud.idu0080.kuller.Kuller#getKullerid(*
     */
    public ee.ttu.tud.idu0080.kuller.KulleridVastus getKullerid() {
    	ServiceLogger.log("Start getKullerid");
        try {
        	CourierServiceService ss = new CourierServiceService(new URL("http://localhost:8080/BPServer/services/CourierServicePort?wsdl"), SERVICE_NAME);
            CourierService port = ss.getCourierServicePort();
        	
            List<Kuller_Type> kullerTypes = port.getAllCouriers().stream()
                    .map(this::buildKullerid)
                    .collect(Collectors.toList());
            
            for (Kuller_Type kt : kullerTypes) { ServiceLogger.log("Courier: [" + kt.getNimi() + "]"); }
            KulleridVastus result = new KulleridVastus();
            result.kuller = kullerTypes;
            ServiceLogger.log("End getKullerid");
            return result;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    private Kuller_Type buildKullerid(Courier courier) {
        Kuller_Type kuller = new Kuller_Type();
        kuller.setKullerId(courier.getEnterprise());
        kuller.setNimi(courier.getName());
        return kuller;
    }

}
