
package org.example.pakkumus;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-05-04T23:29:43.166+03:00
 * Generated source version: 2.7.18
 * 
 */
public final class Pakkumus_PakkumusSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/pakkumus/", "pakkumus");

    private Pakkumus_PakkumusSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Pakkumus_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Pakkumus_Service ss = new Pakkumus_Service(wsdlURL, SERVICE_NAME);
        Pakkumus port = ss.getPakkumusSOAP();  
        
        {
        System.out.println("Invoking teePakkumus...");
        org.example.pakkumus.PakkumusParing _teePakkumus_parameters = new org.example.pakkumus.PakkumusParing();
        _teePakkumus_parameters.setKullerId(-1489096407);
        org.example.pakkumus.TellimusType _teePakkumus_parametersTellimus = new org.example.pakkumus.TellimusType();
        _teePakkumus_parametersTellimus.setOrderId(765525966);
        _teePakkumus_parametersTellimus.setPriceTotal(0.9537038219775552);
        org.example.pakkumus.Seller _teePakkumus_parametersTellimusSeller = new org.example.pakkumus.Seller();
        java.util.List<org.example.pakkumus.Address> _teePakkumus_parametersTellimusSellerAddresses = new java.util.ArrayList<org.example.pakkumus.Address>();
        _teePakkumus_parametersTellimusSeller.getAddresses().addAll(_teePakkumus_parametersTellimusSellerAddresses);
        _teePakkumus_parametersTellimusSeller.setEnterprise(-1850470151);
        _teePakkumus_parametersTellimusSeller.setName("Name-1821100507");
        _teePakkumus_parametersTellimus.setSeller(_teePakkumus_parametersTellimusSeller);
        org.example.pakkumus.Address _teePakkumus_parametersTellimusShippingAddress = new org.example.pakkumus.Address();
        _teePakkumus_parametersTellimusShippingAddress.setAddress(-35063550);
        _teePakkumus_parametersTellimusShippingAddress.setCountry("Country87165835");
        _teePakkumus_parametersTellimusShippingAddress.setCounty("County-454371982");
        _teePakkumus_parametersTellimusShippingAddress.setStreetAddress("StreetAddress907225341");
        _teePakkumus_parametersTellimusShippingAddress.setTownVillage("TownVillage-1674909918");
        _teePakkumus_parametersTellimusShippingAddress.setZipcode("Zipcode100899353");
        _teePakkumus_parametersTellimus.setShippingAddress(_teePakkumus_parametersTellimusShippingAddress);
        _teePakkumus_parameters.setTellimus(_teePakkumus_parametersTellimus);
        org.example.pakkumus.PakkumusVastus _teePakkumus__return = port.teePakkumus(_teePakkumus_parameters);
        System.out.println("teePakkumus.result=" + _teePakkumus__return);


        }

        System.exit(0);
    }

}
